### ISSUE TITLE
ModuleNotFoundError: No module named 'rich'  after ' python -m pip install rich'

### ISSUE THREAD

**Issue by SeekPoint** [OpenLMLab/LOMO#24]
(gh_LOMO) ub2004@ub2004-B85M-A0:~/llm_dev/LOMO$ deepspeed --master_port "1234" --include localhost:"0" src/train_lomo.py config/args_lomo.yaml
[2023-06-28 02:01:44,116] [WARNING] [runner.py:191:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-06-28 02:01:44,142] [INFO] [runner.py:541:main] cmd = /usr/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=1234 --enable_each_rank_log=None src/train_lomo.py config/args_lomo.yaml
[2023-06-28 02:01:46,243] [INFO] [launch.py:229:main] WORLD INFO DICT: {'localhost': [0]}
[2023-06-28 02:01:46,243] [INFO] [launch.py:235:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-06-28 02:01:46,243] [INFO] [launch.py:246:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-06-28 02:01:46,243] [INFO] [launch.py:247:main] dist_world_size=1
[2023-06-28 02:01:46,243] [INFO] [launch.py:249:main] Setting CUDA_VISIBLE_DEVICES=0
PYTHON_PATH /home/ub2004/llm_dev/LOMO
Traceback (most recent call last):
  File "/home/ub2004/llm_dev/LOMO/src/train_lomo.py", line 20, in <module>
    from log import print
  File "/home/ub2004/llm_dev/LOMO/log/__init__.py", line 6, in <module>
    from .logger import logger
  File "/home/ub2004/llm_dev/LOMO/log/logger.py", line 32, in <module>
    from rich.logging import RichHandler
ModuleNotFoundError: No module named 'rich'

**Comment by ayyyq** [comment]
Hello! Please try `pip install rich` in the command line to install `rich`. You can refer to [this url](https://pypi.org/project/rich/) for more information.
