### ISSUE TITLE
adalomo optimizer error

### ISSUE THREAD

**Issue by shawnricecake** [OpenLMLab/LOMO#63]
Hi,

When I use the adalomo optimizer here: https://github.com/OpenLMLab/collie/blob/8746d22eee137cbcb71eceb22cdeba235012e179/collie/optim/adalomo.py

and change the LOMO optimizer into adaLOMO here: 
https://github.com/OpenLMLab/LOMO/blob/5fab460e33fe71ddea04c47352464ffa24a815bd/lomo/src/lomo_trainer.py#L87

after revising some codes and starting running, there is some bug:
```
    @property
    def dp_rank(self):
        return env.dp_rank

    @property
    def world_size(self):
        return env.world_size
```
can not get those rank or world_size before the initialization.

I would appreciate if you can provide the full code for adaLOMO and help reproduce the results claimed in paper.

Thanks
Xuan

**Comment by shawnricecake** [comment]
Also,

how can we set the 'clip_grad_norm' in adalomo?

**Comment by KaiLv69** [comment]
As in https://github.com/OpenLMLab/LOMO/blob/main/adalomo/instruction-tuning/train.py, you should use trainer in collie (dev-branch) instead of lomo_trainer.

**Comment by shawnricecake** [comment]
Hi,

Already tried, the error is the same,

can not get those rank or world_size

**Comment by KaiLv69** [comment]
Did you use the code at https://github.com/OpenLMLab/LOMO/blob/main/adalomo/instruction-tuning/train.py and run like `torchrun --nproc_per_node=8 train.py --optim adalomo --model_size 7b`? Could you pls show your traceback?

**Comment by shawnricecake** [comment]
> Did you use the code at https://github.com/OpenLMLab/LOMO/blob/main/adalomo/instruction-tuning/train.py and run like `torchrun --nproc_per_node=8 train.py --optim adalomo --model_size 7b`? Could you pls show your traceback?


Here,

```
Traceback (most recent call last):
  File "src/quant_train_adalomo.py", line 148, in <module>
    train()
  File "src/quant_train_adalomo.py", line 84, in train
    model, tokenizer, config = get_model()
  File "src/quant_train_adalomo.py", line 51, in get_model
    model = LlamaForCausalLM.from_pretrained(model_name, config=config)
  File "/data/sx/gpt-quant/gpt-finetune/src/collie/models/base.py", line 260, in from_pretrained
    model = cls.from_config(config, init_params=False, get_peft=False)
  File "/data/sx/gpt-quant/gpt-finetune/src/collie/models/base.py", line 126, in from_config
    model.__init__(config)
  File "/home/sx/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 453, in wrapper
    f(module, *args, **kwargs)
  File "/data/sx/gpt-quant/gpt-finetune/src/collie/models/llama/model.py", line 417, in __init__
    self.model = LlamaModel(config)
  File "/home/sx/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 453, in wrapper
    f(module, *args, **kwargs)
  File "/data/sx/gpt-quant/gpt-finetune/src/collie/models/llama/model.py", line 326, in __init__
    self.embed_tokens = tensor_parallel.VocabParallelEmbedding(
  File "/home/sx/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 453, in wrapper
    f(module, *args, **kwargs)
TypeError: __init__() missing 2 required keyword-only arguments: 'init_method' and 'config'
```

**Comment by KaiLv69** [comment]
uh, this is due to the mismatched version of megatron.
The version of `megatron-core` should be `0.2.0` as shown in https://github.com/OpenLMLab/collie/blob/8746d22eee137cbcb71eceb22cdeba235012e179/requirements.txt#L10

**Comment by shawnricecake** [comment]
I will try it asap, thanks for your response!

**Comment by shawnricecake** [comment]
Hi,

Thanks for your help, I can run the finetune with alpaca datasets now, this one should be the AlpacaFarm in the paper, right?

By the way, do you mind provide the instructions for other datasets? like MMLU, BBH, GSM8K, HumanEval

Thanks
Xuan

**Comment by shawnricecake** [comment]
Hi,

For the eval code, I can not run according to the instruction and the traceback is:
```
Traceback (most recent call last):
  File "/home/sx/anaconda3/envs/opencompass/lib/python3.10/site-packages/mmengine/config/config.py", line 1466, in pretty_text
    text, _ = FormatCode(
TypeError: FormatCode() got an unexpected keyword argument 'verify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/sx/gpt-quant/gpt-eval-opencompass/opencompass/run.py", line 373, in <module>
    main()
  File "/data/sx/gpt-quant/gpt-eval-opencompass/opencompass/run.py", line 249, in main
    runner(tasks)
  File "/data/sx/gpt-quant/gpt-eval-opencompass/opencompass/opencompass/runners/base.py", line 39, in __call__
    self.summarize(status)
  File "/data/sx/gpt-quant/gpt-eval-opencompass/opencompass/opencompass/runners/base.py", line 61, in summarize
    for _task, code in status:
  File "/home/sx/anaconda3/envs/opencompass/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/home/sx/anaconda3/envs/opencompass/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/home/sx/anaconda3/envs/opencompass/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/sx/anaconda3/envs/opencompass/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/sx/anaconda3/envs/opencompass/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/sx/gpt-quant/gpt-eval-opencompass/opencompass/opencompass/runners/local.py", line 86, in submit
    res = self._launch(task, gpu_ids, index)
  File "/data/sx/gpt-quant/gpt-eval-opencompass/opencompass/opencompass/runners/local.py", line 115, in _launch
    task.cfg.dump(param_file)
  File "/home/sx/anaconda3/envs/opencompass/lib/python3.10/site-packages/mmengine/config/config.py", line 1556, in dump
    f.write(self.pretty_text)
  File "/home/sx/anaconda3/envs/opencompass/lib/python3.10/site-packages/mmengine/config/config.py", line 1469, in pretty_text
    raise SyntaxError('Failed to format the config file, please '
SyntaxError: Failed to format the config file, please check the syntax of: 
models=[
    dict(type='opencompass.models.HuggingFaceCausalLM',
        abbr='adalomo',
        path='/data/sx/gpt-quant/gpt-finetune/outputs/adalomo-llama-7B/adalomo_lr-0.0005_epoch-3_tp1_dp8_bs16/',
        tokenizer_path='huggyllama/llama-7b',
        tokenizer_kwargs=dict(
            padding_side='left',
            truncation_side='left',
            use_fast=False),
        max_out_len=300,
        max_seq_len=2048,
        batch_size=8,
        model_kwargs=dict(
            device_map='auto'),
        batch_padding=True,
        run_cfg=dict(
            num_gpus=1,
            num_procs=1)),
    ]
datasets=[
    [
            dict(abbr='alpaca_farm',
                type='opencompass.datasets.AlpaceFarmDataset',
                path='tatsu-lab/alpaca_farm',
                name='alpaca_farm_evaluation',
                reader_cfg=dict(
                    input_columns=[
                        'instruction',
                        'input',
                        ],
                    output_column='output'),
                infer_cfg=dict(
                    prompt_template=dict(
                        type='opencompass.openicl.icl_prompt_template.PromptTemplate',
                        template='Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n{input}### Response:'),
                    retriever=dict(
                        type='opencompass.openicl.icl_retriever.ZeroRetriever'),
                    inferencer=dict(
                        type='opencompass.openicl.icl_inferencer.GenInferencer',
                        max_out_len=300)),
                eval_cfg=dict(
                    evaluator=dict(
                        type='opencompass.datasets.alpacaEvaluator'))),
            ],
    ]
work_dir='./outputs/llama7b/20231030_192049'
  0%|                                                                                           | 0/1 [00:00<?, ?it/s]
```

**Comment by shawnricecake** [comment]
Hi,

When I use the eval code, it shows that:
``
Traceback (most recent call last):
  File "/data/sx/gpt-quant/gpt-eval-opencompass/opencompass/opencompass/tasks/openicl_infer.py", line 7, in <module>
    from mmengine.config import Config, ConfigDict
ModuleNotFoundError: No module named 'mmengine'
``

and I have installed mmengine==0.8.2, but it still shows this error, can you share the env for eval?

Thanks

**Comment by shawnricecake** [comment]
by the way, I can not reproduce the result of LOMO on wic dataset in LOMO paper,
would you mind giving the detailed configuration of this training?
Sorry for these questions.

**Comment by shawnricecake** [comment]
> Hi,
> 
> Thanks for your help, I can run the finetune with alpaca datasets now, this one should be the AlpacaFarm in the paper, right?
> 
> By the way, do you mind provide the instructions for other datasets? like MMLU, BBH, GSM8K, HumanEval
> 
> Thanks Xuan

emmmm, actually I mean the other datasets for the finetune process

**Comment by KaiLv69** [comment]
> > Hi,
> > Thanks for your help, I can run the finetune with alpaca datasets now, this one should be the AlpacaFarm in the paper, right?
> > By the way, do you mind provide the instructions for other datasets? like MMLU, BBH, GSM8K, HumanEval
> > Thanks Xuan
> 
> emmmm, actually I mean the other datasets for the finetune process

Let's discuss here :) https://github.com/OpenLMLab/LOMO/issues/64

**Comment by KaiLv69** [comment]
> by the way, I can not reproduce the result of LOMO on wic dataset in LOMO paper, would you mind giving the detailed configuration of this training? Sorry for these questions.

Is the difference significant? Since we use the same dataset and the hyperparamters we used are the same as those in the paper. Maybe it's due to random seed?

**Comment by KaiLv69** [comment]
Close this issue since the initial problem is solved. If and other questions, pls raise another one. :)

**Comment by shawnricecake** [comment]
> > by the way, I can not reproduce the result of LOMO on wic dataset in LOMO paper, would you mind giving the detailed configuration of this training? Sorry for these questions.
> 
> Is the difference significant? Since we use the same dataset and the hyperparamters we used are the same as those in the paper. Maybe it's due to random seed?

I just use the config you gave in this repo, and the LOMO performance on WIC dataset finetune is about 59.6 (while in paper is 71.2)
